# Generated by Django 2.0.7 on 2018-11-23 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='custompermission',
            options={'permissions': (('custom_permission_electronmanage', '器件管理'), ('custom_permission_electrolist', '器件列表'), ('custom_permission_schememanage', '方案管理'), ('custom_permission_schemelist', '方案列表'), ('custom_permission_product', '成品管理'), ('custom_permission_productlist', '成品列表'), ('custom_permission_productcustom', '成品制作'), ('custom_permission_usermanage', '用户管理'), ('custom_permission_userlist', '用户列表'), ('custom_permission_ordermanage', '订单管理'), ('custom_permission_orderlist', '订单列表'), ('custom_permission_config', '平台配置'), ('custom_permission_electrontype', '器件分类'), ('custom_permission_schemetype', '方案分类'), ('custom_permission_producttype', '成品分类'), ('custom_permission_contenttype', '内容管理'), ('custom_permission_freighconfig', '运费配置'), ('custom_permission_website', '网页信息'), ('custom_permission_leavemessage', '反馈'), ('custom_permission_permissionmanage', '权限管理'), ('custom_permission_ manager', '管理员'), ('custom_permission_role', '角色')), 'verbose_name': '自定义权限', 'verbose_name_plural': '自定义权限'},
        ),
    ]
