# Generated by Django 2.0.7 on 2018-11-23 05:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AliPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_at', models.DateField(auto_now=True, verbose_name='更新时间')),
                ('pay_no', models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='微信支付订单号')),
                ('create_at', models.DateField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderElectron',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=1, verbose_name='数量')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='单价')),
            ],
            options={
                'verbose_name': '订单元器件',
                'verbose_name_plural': '订单元器件',
                'db_table': 'm_order_electron',
            },
        ),
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('create_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('update_at', models.DateField(auto_now=True, verbose_name='更新时间')),
                ('order_id', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='订单号')),
                ('total_count', models.IntegerField(default=1, verbose_name='商品总数')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='商品总金额')),
                ('freight', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='运费')),
                ('pay_method', models.SmallIntegerField(choices=[(1, '支付宝'), (2, '微信')], default=1, verbose_name='支付方式')),
                ('status', models.SmallIntegerField(choices=[(1, '待支付'), (2, '待发货'), (3, '待收货'), (4, '已完成'), (5, '已取消'), (6, '已退款')], default=2, verbose_name='订单状态')),
                ('Courier_company', models.CharField(blank=True, max_length=32, null=True, verbose_name='快递公司')),
                ('Courier_no', models.CharField(blank=True, max_length=64, null=True, verbose_name='快递单号')),
                ('Courier_time', models.DateTimeField(blank=True, null=True, verbose_name='发货时间')),
                ('receive_goods', models.BooleanField(default=False, verbose_name='是否收货')),
                ('receipt', models.SmallIntegerField(choices=[(1, '不须发票'), (2, '个人'), (3, '企业')], default=1, verbose_name='发票类型')),
                ('rel_name', models.CharField(blank=True, max_length=188, null=True, verbose_name='个人发票抬头')),
                ('company_name', models.CharField(blank=True, help_text='公司名称', max_length=188, null=True, verbose_name='公司名称')),
                ('company_tax_number', models.CharField(blank=True, help_text='电话号码', max_length=188, null=True, verbose_name='纳税识别号')),
                ('return_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='退款金额')),
                ('describe', models.TextField(blank=True, null=True, verbose_name='退款描述')),
            ],
            options={
                'verbose_name': '订单基本信息',
                'verbose_name_plural': '订单基本信息',
                'db_table': 'm_order_info',
            },
        ),
        migrations.CreateModel(
            name='WechatPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_at', models.DateField(auto_now=True, verbose_name='更新时间')),
                ('pay_no', models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='微信支付订单号')),
                ('create_at', models.DateField(auto_now_add=True, verbose_name='创建时间')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='we_order', to='order.OrderInfo', verbose_name='订单')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
