# Generated by Django 2.0.7 on 2018-11-23 05:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('electron', '0002_auto_20181123_1355'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.Address', verbose_name='收货地址'),
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='下单用户'),
        ),
        migrations.AddField(
            model_name='orderelectron',
            name='eles',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='electron.Electron', verbose_name='订单商品'),
        ),
        migrations.AddField(
            model_name='orderelectron',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eles', to='order.OrderInfo', verbose_name='订单'),
        ),
        migrations.AddField(
            model_name='alipayment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ali_order', to='order.OrderInfo', verbose_name='订单'),
        ),
    ]
