# Generated by Django 2.0.7 on 2018-11-23 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('electron', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=188, verbose_name='方案名称')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='价格')),
                ('tags', models.CharField(blank=True, max_length=566, null=True, verbose_name='标签')),
                ('images', models.CharField(blank=True, max_length=566, null=True, verbose_name='图片')),
                ('source_code', models.CharField(blank=True, max_length=566, null=True, verbose_name='源码')),
                ('code_name', models.CharField(blank=True, max_length=188, null=True, verbose_name='源码名称')),
                ('desc_specific', models.TextField(blank=True, null=True, verbose_name='特性')),
                ('describe', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('is_reference', models.BooleanField(default=False, verbose_name='参考设计')),
                ('views', models.IntegerField(blank=True, default=0, null=True, verbose_name='浏览量')),
                ('source_web', models.CharField(blank=True, max_length=366, null=True, verbose_name='来源站点')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='抓取时间')),
                ('download_count', models.IntegerField(blank=True, default=0, null=True, verbose_name='下载次数')),
                ('contact_name', models.CharField(blank=True, max_length=166, null=True, verbose_name='联系人')),
                ('contact_tel', models.CharField(blank=True, max_length=166, null=True, verbose_name='联系电话')),
                ('enterprise', models.CharField(blank=True, max_length=166, null=True, verbose_name='企业名称')),
                ('contact_qq', models.CharField(blank=True, max_length=166, null=True, verbose_name='联系QQ')),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='联系邮箱')),
            ],
            options={
                'verbose_name': '方案',
                'verbose_name_plural': '方案',
                'db_table': 'm_scheme',
            },
        ),
        migrations.CreateModel(
            name='SchemeCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=188, unique=True, verbose_name='类目描述')),
                ('image', models.CharField(blank=True, max_length=288, null=True, verbose_name='图片')),
            ],
            options={
                'verbose_name': '方案类型',
                'verbose_name_plural': '方案类型',
                'db_table': 'm_scheme_category',
            },
        ),
        migrations.CreateModel(
            name='SchemeConsumer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_share', models.BooleanField(default=False, verbose_name='分享')),
                ('is_pay', models.BooleanField(default=False, verbose_name='付费')),
            ],
            options={
                'verbose_name': '方案消费者',
                'verbose_name_plural': '方案消费者',
                'db_table': 'm_scheme_consumer',
            },
        ),
        migrations.CreateModel(
            name='SchemeDocuments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='文档名称', max_length=188, null=True, verbose_name='文档名称')),
                ('url', models.CharField(blank=True, max_length=288, null=True, verbose_name='文件路径')),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='scheme.Scheme')),
            ],
            options={
                'verbose_name': '方案技术文档',
                'verbose_name_plural': '方案技术文档',
                'db_table': 'm_scheme_documents',
            },
        ),
        migrations.CreateModel(
            name='SchemeElectron',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_des', models.CharField(blank=True, max_length=266, null=True, verbose_name='描述')),
                ('is_key', models.BooleanField(default=False)),
                ('is_record', models.BooleanField(default=False)),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('model_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sheme_electrons', to='electron.Electron')),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='electrons', to='scheme.Scheme')),
            ],
            options={
                'verbose_name': '方案元器件',
                'verbose_name_plural': '方案元器件',
                'db_table': 'm_scheme_electron',
            },
        ),
        migrations.CreateModel(
            name='SchemeSystemDesign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='名称', max_length=166, verbose_name='名称')),
                ('image', models.CharField(max_length=566, verbose_name='图片链接')),
                ('download_count', models.IntegerField(default=0, verbose_name='下载量')),
                ('scheme', models.ForeignKey(help_text='方案', on_delete=django.db.models.deletion.CASCADE, related_name='designs', to='scheme.Scheme', verbose_name='方案')),
            ],
            options={
                'verbose_name': '方案系统框图',
                'verbose_name_plural': '方案系统框图',
                'db_table': 'm_scheme_system_design',
            },
        ),
        migrations.CreateModel(
            name='SchemeVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=288, null=True, verbose_name='视频地址')),
                ('name', models.CharField(blank=True, max_length=288, null=True, verbose_name='视频名称')),
                ('title', models.CharField(max_length=188, verbose_name='标题')),
                ('is_primary', models.BooleanField(default=False, verbose_name='是否是主视频')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='scheme.Scheme', verbose_name='方案')),
            ],
            options={
                'verbose_name': '方案视频',
                'verbose_name_plural': '方案视频',
                'db_table': 'm_scheme_video',
            },
        ),
        migrations.CreateModel(
            name='SimilarScheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similars', to='scheme.Scheme', verbose_name='元器件')),
                ('similar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar_schemes', to='scheme.Scheme', verbose_name='可替换方案')),
            ],
            options={
                'verbose_name': '可替换元器件',
                'verbose_name_plural': '可替换元器件',
                'db_table': 'm_scheme_similar',
            },
        ),
    ]
