# Generated by Django 2.0.7 on 2018-11-23 05:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scheme', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schemeconsumer',
            name='consumer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='消费者'),
        ),
        migrations.AddField(
            model_name='schemeconsumer',
            name='scheme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheme.Scheme', verbose_name='方案'),
        ),
        migrations.AddField(
            model_name='schemecategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='scheme.SchemeCategory'),
        ),
        migrations.AddField(
            model_name='scheme',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheme.SchemeCategory', verbose_name='方案类型'),
        ),
        migrations.AddField(
            model_name='scheme',
            name='consumer',
            field=models.ManyToManyField(related_name='scheme_consumers', through='scheme.SchemeConsumer', to=settings.AUTH_USER_MODEL, verbose_name='方案的消费者'),
        ),
        migrations.AddField(
            model_name='scheme',
            name='scheme_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scheme_user', to=settings.AUTH_USER_MODEL, verbose_name='下单用户'),
        ),
    ]
