# Generated by Django 2.0.7 on 2018-11-23 05:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('electron', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='universalcomment',
            name='consumer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumer_comment', to=settings.AUTH_USER_MODEL, verbose_name='评论人'),
        ),
        migrations.AddField(
            model_name='similarelectron',
            name='electron',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar_electron', to='electron.Electron', verbose_name='元器件'),
        ),
        migrations.AddField(
            model_name='similarelectron',
            name='similar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar_electrons', to='electron.Electron', verbose_name='可替换元器件'),
        ),
        migrations.AddField(
            model_name='pintopin',
            name='electron',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pin_electron', to='electron.Electron', verbose_name='元器件'),
        ),
        migrations.AddField(
            model_name='pintopin',
            name='pin_to_pin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pin_to_pin_electron', to='electron.Electron', verbose_name='PintoPin元器件'),
        ),
        migrations.AddField(
            model_name='electronvideo',
            name='electron',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_electron', to='electron.Electron', verbose_name='元器件'),
        ),
        migrations.AddField(
            model_name='electronsupplier',
            name='electron',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='electrons_supplier', to='electron.Electron', verbose_name='电子元器件'),
        ),
        migrations.AddField(
            model_name='electronsupplier',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electron.Supplier', verbose_name='供应商'),
        ),
        migrations.AddField(
            model_name='electronkwargsvaluefront',
            name='electron',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='electron_kwargs', to='electron.Electron', verbose_name='元器件'),
        ),
        migrations.AddField(
            model_name='electronkwargsvaluefront',
            name='kwargs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kwargs', to='electron.ElectronKwargs', verbose_name='参数分类'),
        ),
        migrations.AddField(
            model_name='electronkwargsvalue',
            name='kwargs',
            field=models.ForeignKey(help_text='参数', on_delete=django.db.models.deletion.CASCADE, related_name='values', to='electron.ElectronKwargs', verbose_name='参数'),
        ),
        migrations.AddField(
            model_name='electronkwargs',
            name='electron',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electron.ElectronCategory', verbose_name='类型'),
        ),
        migrations.AddField(
            model_name='electronconsumer',
            name='consumer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumer_electron', to=settings.AUTH_USER_MODEL, verbose_name='消费者'),
        ),
        migrations.AddField(
            model_name='electronconsumer',
            name='electron',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='electron_consumer', to='electron.Electron', verbose_name='电子元器件'),
        ),
        migrations.AddField(
            model_name='electroncircuitdiagram',
            name='electron',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='electron_system', to='electron.Electron', verbose_name='电子元器件'),
        ),
        migrations.AddField(
            model_name='electroncategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='electron.ElectronCategory'),
        ),
        migrations.AddField(
            model_name='electron',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='electrons', to='electron.ElectronCategory', verbose_name='类型'),
        ),
        migrations.AddField(
            model_name='electron',
            name='supplier',
            field=models.ManyToManyField(through='electron.ElectronSupplier', to='electron.Supplier', verbose_name='供应商'),
        ),
        migrations.AlterUniqueTogether(
            name='similarelectron',
            unique_together={('electron', 'similar')},
        ),
        migrations.AlterUniqueTogether(
            name='pintopin',
            unique_together={('electron', 'pin_to_pin')},
        ),
    ]
